<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Assuming category IDs: Chiên=1, Hấp=2, Xào=3, Kho=4, Đồ ngọt=5, Khác=6
        DB::table('foods')->insert([
            [
                'name' => 'Gà Rán',
                'slug' => Str::slug('Gà Rán'),
                'category_id' => 6, // Chiên
                'description' => 'Gà rán giòn rụm thơm ngon.',
                'price' => 50000.00,
                'sold' => 150,
                'discount' => 10,
                'rating' => 4.50,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chả Giò',
                'slug' => Str::slug('Chả Giò'),
                'category_id' => 6, // Chiên
                'description' => 'Chả giò truyền thống, vỏ giòn rụm.',
                'price' => 30000.00,
                'sold' => 120,
                'discount' => 0,
                'rating' => 4.20,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Bao',
                'slug' => Str::slug('Bánh Bao'),
                'category_id' => 2, // Hấp
                'description' => 'Bánh bao nóng hổi nhân thịt.',
                'price' => 15000.00,
                'sold' => 100,
                'discount' => 0,
                'rating' => 4.00,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mì Xào Hải Sản',
                'slug' => Str::slug('Mì Xào Hải Sản'),
                'category_id' => 3, // Xào
                'description' => 'Mì xào hải sản tươi ngon, đậm đà.',
                'price' => 65000.00,
                'sold' => 80,
                'discount' => 5,
                'rating' => 4.70,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cá Kho Tộ',
                'slug' => Str::slug('Cá Kho Tộ'),
                'category_id' => 4, // Kho
                'description' => 'Cá kho tộ đậm chất quê hương.',
                'price' => 75000.00,
                'sold' => 60,
                'discount' => 0,
                'rating' => 4.80,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Donut',
                'slug' => Str::slug('Bánh Donut'),
                'category_id' => 5, // Đồ ngọt
                'description' => 'Bánh donut mềm xốp nhiều vị.',
                'price' => 20000.00,
                'sold' => 200,
                'discount' => 0,
                'rating' => 4.10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Snack Khoai Tây',
                'slug' => Str::slug('Snack Khoai Tây'),
                'category_id' => 1, // Khác
                'description' => 'Snack khoai tây giòn tan.',
                'price' => 10000.00,
                'sold' => 300,
                'discount' => 0,
                'rating' => 3.90,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cơm Gà Chiên Nước Mắm',
                'slug' => Str::slug('Cơm Gà Chiên Nước Mắm'),
                'category_id' => 6,
                'description' => 'Cơm gà chiên nước mắm thơm ngon.',
                'price' => 50000,
                'sold' => 130,
                'discount' => 5,
                'rating' => 4.6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mì Tương đen',
                'slug' => Str::slug('Mì Tương đen'),
                'category_id' => 3,
                'description' => 'Mì trộn đậm vị, không nước, nhiều topping.',
                'price' => 45000,
                'sold' => 110,
                'discount' => 0,
                'rating' => 4.4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Xôi Mặn Thập Cẩm',
                'slug' => Str::slug('Xôi Mặn Thập Cẩm'),
                'category_id' => 6,
                'description' => 'Xôi dẻo, topping chả, lạp xưởng, trứng.',
                'price' => 30000,
                'sold' => 150,
                'discount' => 0,
                'rating' => 4.3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Mì Thịt Nướng',
                'slug' => Str::slug('Bánh Mì Thịt Nướng'),
                'category_id' => 1,
                'description' => 'Bánh mì giòn rụm, thịt nướng thơm lừng.',
                'price' => 25000,
                'sold' => 200,
                'discount' => 0,
                'rating' => 4.8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Bao Nhân Trứng Muối',
                'slug' => Str::slug('Bánh Bao Nhân Trứng Muối'),
                'category_id' => 2,
                'description' => 'Bánh bao nóng hổi, nhân mặn béo ngậy.',
                'price' => 18000,
                'sold' => 95,
                'discount' => 0,
                'rating' => 4.1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Tráng Cuốn',
                'slug' => Str::slug('Bánh Tráng Cuốn'),
                'category_id' => 1,
                'description' => 'Bánh tráng cuốn khô, trứng, khô bò, rau răm.',
                'price' => 25000,
                'sold' => 120,
                'discount' => 0,
                'rating' => 4.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Bò Nướng',
                'slug' => Str::slug('Bánh Bò Nướng'),
                'category_id' => 5,
                'description' => 'Bánh bò mềm, thơm nước cốt dừa.',
                'price' => 12000,
                'sold' => 140,
                'discount' => 0,
                'rating' => 4.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nem Chua Rán',
                'slug' => Str::slug('Nem Chua Rán'),
                'category_id' => 6,
                'description' => 'Nem chua rán giòn, chấm tương ớt.',
                'price' => 25000,
                'sold' => 130,
                'discount' => 0,
                'rating' => 4.3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khoai Tây Lắc Phô Mai',
                'slug' => Str::slug('Khoai Tây Lắc Phô Mai'),
                'category_id' => 1,
                'description' => 'Snack khoai lắc bột phô mai béo ngậy.',
                'price' => 20000,
                'sold' => 250,
                'discount' => 0,
                'rating' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Gạo Tokbokki Chiên',
                'slug' => Str::slug('Bánh Gạo Tokbokki Chiên'),
                'category_id' => 6,
                'description' => 'Tokbokki chiên giòn kiểu Hàn, cay nhẹ.',
                'price' => 32000,
                'sold' => 100,
                'discount' => 0,
                'rating' => 4.3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Khoai Mì Nướng',
                'slug' => Str::slug('Bánh Khoai Mì Nướng'),
                'category_id' => 5,
                'description' => 'Bánh khoai mì truyền thống, giòn vỏ mềm trong.',
                'price' => 18000,
                'sold' => 160,
                'discount' => 0,
                'rating' => 4.2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Bao Chiên Nhân Mặn',
                'slug' => Str::slug('Bánh Bao Chiên Nhân Mặn'),
                'category_id' => 2,
                'description' => 'Bánh bao chiên lớp vỏ giòn, nhân thịt.',
                'price' => 20000,
                'sold' => 105,
                'discount' => 0,
                'rating' => 4.1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bắp Xào Bơ Tỏi',
                'slug' => Str::slug('Bắp Xào Bơ Tỏi'),
                'category_id' => 1,
                'description' => 'Bắp ngọt xào bơ tỏi thơm béo.',
                'price' => 22000,
                'sold' => 180,
                'discount' => 0,
                'rating' => 4.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chả Cá Viên',
                'slug' => Str::slug('Chả Cá Viên'),
                'category_id' => 6,
                'description' => 'Chả cá viên thơm ngon.',
                'price' => 27000,
                'sold' => 90,
                'discount' => 0,
                'rating' => 4.2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
